# Generated by Django 5.0.3 on 2025-06-29 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecertification',
            name='approval_status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Deferido', 'Deferido'), ('Indeferido', 'Indeferido'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='recognitionofpriorlearning',
            name='approval_status',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Deferido', 'Deferido'), ('Indeferido', 'Indeferido'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20),
        ),
    ]
