# Generated by Django 5.0.3 on 2025-04-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'ordering': ['name', 'is_active'], 'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.AddField(
            model_name='disciplines',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates if the discipline is active and can be used.', verbose_name='Is Active'),
        ),
    ]
