# Generated by Django 5.0.3 on 2025-05-18 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_disciplines_options_disciplines_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='file_data',
        ),
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=models.CharField(editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('CRE', 'Aguardando período de análise'), ('CANCELED', 'Cancelado pelo Aluno'), ('C_CRE', 'Cancelado pelo Ensino'), ('A_CRE', 'Analisado pelo Ensino'), ('COORD', 'Em análise do Coordenador'), ('C_COORD', 'Cancelado pelo Coordenador'), ('A_COORD', 'Analisado pelo Coordenador'), ('PROF', 'Em análise do Professor'), ('RJ_PROF', 'Rejeitado pelo Professor'), ('A_PROF', 'Analisado pelo Professor'), ('IN_AP_COORD', 'Em homologação do Coordenador'), ('R_COORD', 'Retornado pelo Coordenador'), ('RJ_COORD', 'Rejeitado pelo Coordenador'), ('AP_COORD', 'Aprovado pelo Coordenador'), ('IN_AP_CRE', 'Em homologação do Ensino'), ('R_CRE', 'Retornado pelo Ensino'), ('RJ_CRE', 'Rejeitado pelo Ensino'), ('AP_CRE', 'Aprovado pelo Ensino')], max_length=20),
        ),
    ]
