# Generated by Django 5.0.3 on 2025-07-02 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_knowledgecertification_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['initial_step_date']},
        ),
    ]
