# Generated by Django 5.0.3 on 2025-05-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_attachment_file_data_alter_attachment_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
