# Generated by Django 5.0.3 on 2025-05-19 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_accesstoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
    ]
