# Generated by Django 5.0.3 on 2025-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_delete_accesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='drive_folder_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
