# Generated by Django 5.0.3 on 2025-05-27 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_student_drive_folder_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplines',
            name='professors',
        ),
        migrations.AddField(
            model_name='disciplines',
            name='main_objetive',
            field=models.TextField(blank=True, help_text='Select the main_objetive for this discipline:', max_length=1000, verbose_name='Professors'),
        ),
        migrations.AlterField(
            model_name='disciplines',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Enter the syllabus of the discipline:', max_length=1500, verbose_name='Syllabus'),
        ),
    ]
