# Generated by Django 5.0.3 on 2025-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_recognitionofpriorlearning_previous_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognitionofpriorlearning',
            name='previous_course',
            field=models.CharField(max_length=255),
        ),
    ]
