# Generated by Django 5.0.3 on 2025-05-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_recognitionofpriorlearning_previous_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('CRE', 'Solicitação criada'), ('CANCELED', 'Cancelado pelo Aluno'), ('C_CRE', 'Cancelado pelo Ensino'), ('A_CRE', 'Encaminhado para o Coordenador'), ('COORD', 'Em análise do Coordenador'), ('C_COORD', 'Cancelado pelo Coordenador'), ('A_COORD', 'Analisado pelo Coordenador'), ('PROF', 'Em análise do Professor'), ('RJ_PROF', 'Rejeitado pelo Professor'), ('A_PROF', 'Analisado pelo Professor'), ('IN_AP_COORD', 'Em homologação do Coordenador'), ('R_COORD', 'Retornado pelo Coordenador'), ('RJ_COORD', 'Rejeitado pelo Coordenador'), ('AP_COORD', 'Aprovado pelo Coordenador'), ('IN_AP_CRE', 'Em aguardo para divulgação'), ('R_CRE', 'Retornado pelo Ensino'), ('RJ_CRE', 'Rejeitado pelo Ensino'), ('AP_CRE', 'Finalizado e divulgado')], max_length=20),
        ),
    ]
