# Generated by Django 5.0.3 on 2025-06-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_step_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='link',
            field=models.URLField(max_length=400),
        ),
    ]
