# Generated by Django 5.0.3 on 2025-06-04 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_notice_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ['-publication_date']},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='result_homologation',
        ),
    ]
