# Generated by Django 5.0.3 on 2025-06-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_knowledgecertification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstractuser',
            options={'ordering': ['-is_active', 'name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-is_active', 'name']},
        ),
        migrations.AlterModelOptions(
            name='disciplines',
            options={'ordering': ['-is_active', 'name'], 'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.AlterModelOptions(
            name='ppc',
            options={'ordering': ['-is_active', 'name']},
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ppc',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='step',
            name='status',
            field=models.CharField(choices=[('CRE', 'Solicitação criada'), ('CANCELED', 'Cancelado pelo Aluno'), ('C_CRE', 'Cancelado pelo Ensino'), ('A_CRE', 'Encaminhado para o Coordenador'), ('COORD', 'Em análise do Coordenador'), ('C_COORD', 'Cancelado pelo Coordenador'), ('A_COORD', 'Analisado pelo Coordenador'), ('PROF', 'Em análise do Professor'), ('RJ_PROF', 'Rejeitado pelo Professor'), ('A_PROF', 'Analisado pelo Professor'), ('IN_AP_COORD', 'Em homologação do Coordenador'), ('R_COORD', 'Retornado pelo Coordenador'), ('RJ_COORD', 'Rejeitado pelo Coordenador'), ('AP_COORD', 'Homologado pelo Coordenador'), ('IN_AP_CRE', 'Etapa de Registro do Ensino'), ('R_CRE', 'Retornado pelo Ensino'), ('RJ_CRE', 'Rejeitado pelo Ensino'), ('AP_CRE', 'Finalizado')], max_length=20),
        ),
    ]
